### ISSUE TITLE
sql/delete_user.sql uses SHA2

### ISSUE THREAD

**Issue by thegleek** [Freetable/network-services#1]
SHA2 only works with msql 5.5.x+, this can be later be placed into production

**Comment by StephanieSunshine** [comment]
https://github.com/Freetable/network-services/blob/master/sql/delete_user.sql

SHA512 hash happens client side, updated to reflect this.

Commit Log: https://github.com/Freetable/network-services/commit/a5a6bd4ad3f9b85bb0c156cc200b62d0428e6a74
