### ISSUE TITLE
sql/set_user_password.sql uses SHA2

### ISSUE THREAD

**Issue by thegleek** [Freetable/network-services#2]
needs to be removed until production development comes along

**Comment by StephanieSunshine** [comment]
https://github.com/Freetable/network-services/blob/master/sql/set_user_password.sql

Updated to reflect that SHA512 is not generated client side.

Commit Log: https://github.com/Freetable/network-services/commit/6cfe23cfa601bf17af7bb2a05ab58ff57c34a942
